lee = Author.create({first_name:"Harper", last_name:"Lee", year_born: 1926, year_died: :nill, image: "https://d.gr-assets.com/authors/1188820730p8/1825.jpg", bio: "Harper Lee, known as Nelle, was born in the Alabama town of Monroeville, the youngest of four children of Amasa Coleman Lee and Frances Cunningham Finch Lee. Her father, a former newspaper editor and proprietor, was a lawyer who served on the state legislature from 1926 to 1938. As a child, Lee was a tomboy and a precocious reader, and enjoyed the friendship of her schoolmate and neighbor, the young Truman Capote."})
kingsolver = Author.create({first_name:"Barbara", last_name:"Kingsolver", year_born: 1955, year_died: :nill, image: "http://s3.amazonaws.com/media.wbur.org/wordpress/11/files/2012/11/1109_butterflies-author.jpg", bio: "Barbara Kingsolver is an American novelist, essayist, and poet. She was raised in rural Kentucky and lived briefly in Africa in her early childhood. Kingsolver earned degrees in Biology at DePauw University and the University of Arizona and worked as a freelance writer before she began writing novels. Her most famous works include The Poisonwood Bible, the tale of a missionary family in the Congo, and Animal, Vegetable, Miracle, a non-fiction account of her family's attempts to eat locally. Her work often focuses on topics such as social justice, biodiversity, and the interaction between humans and their communities and environments."})
fitzgerald = Author.create({first_name:"F. Scott", last_name:"Fitzgerald", year_born: 1896, year_died: 1940, image: "https://d.gr-assets.com/authors/1427040571p8/3190.jpg", bio: "Francis Scott Key Fitzgerald was an American writer of novels and short stories, whose works have been seen as evocative of the Jazz Age, a term he himself allegedly coined. He is regarded as one of the greatest twentieth century writers. Fitzgerald was of the self-styled 'Lost Generation,' Americans born in the 1890s who came of age during World War I. He finished four novels, left a fifth unfinished, and wrote dozens of short stories that treat themes of youth, despair, and age."})
orwell = Author.create({first_name:"George", last_name:"Orwell", year_born: 1903, year_died: 1950, image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/George-orwell-BBC.jpg", bio: "Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism. Orwell's influence on contemporary culture, popular and political, continues decades after his death. Several of his neologisms, along with the term 'Orwellian' — now a byword for any oppressive or manipulative social phenomenon opposed to a free society — have entered the vernacular."})
salinger = Author.create({first_name: "J.D.", last_name: "Salinger", year_born: 1919, year_died: 2010, image: "https://d.gr-assets.com/authors/1288777679p8/819789.jpg", bio: "Jerome David Salinger was an American author, best known for his 1951 novel The Catcher in the Rye, as well as his reclusive nature. His last original published work was in 1965; he gave his last interview in 1980. Raised in Manhattan, Salinger began writing short stories while in secondary school, and published several stories in the early 1940s before serving in World War II. In 1948 he published the critically acclaimed story 'A Perfect Day for Bananafish' in The New Yorker magazine, which became home to much of his subsequent work. In 1951 Salinger released his novel The Catcher in the Rye, an immediate popular success. His depiction of adolescent alienation and loss of innocence in the protagonist Holden Caulfield was influential, especially among adolescent readers. The novel remains widely read and controversial, selling around 250,000 copies a year."})
plath = Author.create({first_name: "Sylvia", last_name: "Plath", year_born: 1932, year_died: 1963, image: "https://upload.wikimedia.org/wikipedia/en/e/e4/Sylvia_plath.jpg", bio: "Known primarily for her poetry, Plath also wrote a semi-autobiographical novel, The Bell Jar, under the pseudonym Victoria Lucas. The book's protagonist, Esther Greenwood, is a bright, ambitious student at Smith College who begins to experience a mental breakdown while interning for a fashion magazine in New York. The plot parallels Plath's experience interning at Mademoiselle magazine and subsequent mental breakdown and suicide attempt."})
austen = Author.create({first_name: "Jane", last_name: "Austen", year_born: 1775, year_died: 1817, image: "https://d.gr-assets.com/authors/1380085320p8/1265.jpg", bio: "Jane Austen (16 December 1775 – 18 July 1817) was an English novelist whose works of romantic fiction, set among the landed gentry, earned her a place as one of the most widely read writers in English literature, her realism and biting social commentary cementing her historical importance among scholars and critics."})

mockingbird = Book.create({title: "To Kill a Mockingbird", release_year: 1960, image: "https://upload.wikimedia.org/wikipedia/en/7/79/To_Kill_a_Mockingbird.JPG", synopsis: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic."})
catcher = Book.create({title: "Catcher In The Rye", release_year: 1951, image: "http://www.katherinepreston.com/blog/wp-content/uploads/2012/07/catcher-in-the-rye.jpg", synopsis: "Since his debut in 1951 as The Catcher in the Rye, Holden Caulfield has been synonymous with 'cynical adolescent.' Holden narrates the story of a couple of days in his sixteen-year-old life, just after he's been expelled from prep school, in a slang that sounds edgy even today and keeps this novel on banned book lists. His constant wry observations about what he encounters, from teachers to phonies (the two of course are not mutually exclusive) capture the essence of the eternal teenage experience of alienation."})
zooey = Book.create({title: "Franny and Zooey", release_year: 1961, image: "http://i2.listal.com/image/2616/600full-franny-and-zooey-cover.jpg", synopsis: "The short story, Franny, takes place in an unnamed college town and tells the tale of an undergraduate who is becoming disenchanted with the selfishness and inauthenticity she perceives all around her. The novella, Zooey, is named for Zooey Glass, the second-youngest member of the Glass family. As his younger sister, Franny, suffers a spiritual and existential breakdown in her parents' Manhattan living room -- leaving Bessie, her mother, deeply concerned -- Zooey comes to her aid, offering what he thinks is brotherly love, understanding, and words of sage advice."})
poisonwood = Book.create({title: "The Poisonwood Bible", release_year: 1998, image: "https://upload.wikimedia.org/wikipedia/en/7/79/Poisonwood_Bible.jpg", synopsis: "The Poisonwood Bible is a story told by the wife and four daughters of Nathan Price, a fierce, evangelical Baptist who takes his family and mission to the Belgian Congo in 1959. They carry with them everything they believe they will need from home, but soon find that all of it -- from garden seeds to Scripture -- is calamitously transformed on African soil. What follows is a suspenseful epic of one family's tragic undoing and remarkable reconstruction over the course of three decades in postcolonial Africa."})
gatsby = Book.create({title: "The Great Gatsby", release_year: 1925, image: "http://a5.files.biography.com/image/upload/c_fit,cs_srgb,dpr_1.0,q_80,w_300/MTI5MzY0OTk4NTM0MjQwNzM0.jpg", synopsis: "F. Scott Fitzgerald’s third book stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted “gin was the national drink and sex the national obsession,” it is an exquisitely crafted tale of America in the 1920s."})
eighty_four = Book.create({title: "1984", release_year: 1949, image: "https://d.gr-assets.com/books/1348990566l/5470.jpg", synopsis: "The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever. 1984 is still the great modern classic of 'negative utopia' -a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions -a power that seems to grow, not lessen, with the passage of time."})
bell = Book.create({title: "The Bell Jar", release_year: 1963, image: "http://blog.sevenponds.com/wp-content/uploads/2012/12/belljar.jpg", synopsis: "Sylvia Plath's shocking, realistic, and intensely emotional novel about a woman falling into the grip of insanity."})
pride = Book.create({title: "Pride and Prejudice", release_year: 1813, image: "http://blog.mugglenet.com/wp-content/uploads/2013/09/pride-prejudice.jpg", synopsis: "'It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.' So begins Pride and Prejudice, Jane Austen's witty comedy of manners--one of the most popular novels of all time--that features splendidly civilized sparring between the proud Mr. Darcy and the prejudiced Elizabeth Bennet as they play out their spirited courtship in a series of eighteenth-century drawing-room intrigues."})
emma = Book.create({title: "Emma", release_year: 1815, image: "http://d.gr-assets.com/books/1373627931l/6969.jpg", synopsis: "Beautiful, clever, rich - and single - Emma Woodhouse is perfectly content with her life and sees no need for either love or marriage. Nothing, however, delights her more than interfering in the romantic lives of others. But when she ignores the warnings of her good friend Mr. Knightley and attempts to arrange a suitable match for her protegee Harriet Smith, her carefully laid plans soon unravel and have consequences that she never expected. With its imperfect but charming heroine and its witty and subtle exploration of relationships, Emma is often seen as Jane Austen's most flawless work."})
mansfield = Book.create({title: "Mansfield Park", release_year: 1814, image: "https://theliteraryomnivore.files.wordpress.com/2010/10/austenmansfieldpark.jpg", synopsis: "Taken from the poverty of her parents' home, Fanny Price is brought up with her rich cousins at Mansfield Park, acutely aware of her humble rank and with only her cousin Edmund as an ally. When Fanny's uncle is absent in Antigua, Mary Crawford and her brother Henry arrive in the neighbourhood, bringing with them London glamour and a reckless taste for flirtation. As her female cousins vie for Henry's attention, and even Edmund falls for Mary's dazzling charms, only Fanny remains doubtful about the Crawfords' influence and finds herself more isolated than ever."})

salinger.books << [catcher, zooey]
kingsolver.books << poisonwood
fitzgerald.books << gatsby
orwell.books << eighty_four
lee.books << mockingbird
plath.books << bell
austen.books << [pride, emma, mansfield]

guest = User.create({name: "Guest", email: "guest@test.com", password: "mylibrary"})
