martel = Author.create({first_name:"Yann", last_name:"Martel", year_born: 1963, year_died: :nill, image: "http://www.cbc.ca/books/arts_booker-best-2_220v.jpg", bio: "Yann Martel is the author of Life of Pi, the #1 international bestseller and winner of the 2002 Man Booker (among many other prizes). He is also the award-winning author of The Facts Behind the Helsinki Roccamatios (winner of the Journey Prize), Self, Beatrice & Virgil, and 101 Letters to a Prime Minister. Born in Spain in 1963, Martel studied philosophy at Trent University, worked at odd jobs—tree planter, dishwasher, security guard—and traveled widely before turning to writing. He lives in Saskatoon, Canada, with the writer Alice Kuipers and their four children."})
chabon = Author.create({first_name:"Michael", last_name:"Chabon", year_born: 1963, year_died: :nill, image: "http://www.newyorker.com/wp-content/uploads/2012/09/chabon.jpg", bio: "Michael Chabon is an acclaimed and bestselling author whose works include the Pulitzer Prize–winning novel The Amazing Adventures of Kavalier & Clay (2000). Chabon achieved literary fame at age twenty-four with his first novel, The Mysteries of Pittsburgh (1988), which was a major critical and commercial success. He then published Wonder Boys (1995), another bestseller, which was made into a film starring Michael Douglas. One of America’s most distinctive voices, Chabon has been called “a magical prose stylist” by the New York Times Book Review, and is known for his lively writing, nostalgia for bygone modes of storytelling, and deep empathy for the human predicament."})
kingsolver = Author.create({first_name:"Barbara", last_name:"Kingsolver", year_born: 1955, year_died: :nill, image: "http://s3.amazonaws.com/media.wbur.org/wordpress/11/files/2012/11/1109_butterflies-author.jpg", bio: "Barbara Kingsolver is an American novelist, essayist, and poet. She was raised in rural Kentucky and lived briefly in Africa in her early childhood. Kingsolver earned degrees in Biology at DePauw University and the University of Arizona and worked as a freelance writer before she began writing novels. Her most famous works include The Poisonwood Bible, the tale of a missionary family in the Congo, and Animal, Vegetable, Miracle, a non-fiction account of her family's attempts to eat locally. Her work often focuses on topics such as social justice, biodiversity, and the interaction between humans and their communities and environments."})
fitzgerald = Author.create({first_name:"F. Scott", last_name:"Fitzgerald", year_born: 1896, year_died: 1940, image: "https://d.gr-assets.com/authors/1427040571p8/3190.jpg", bio: "Francis Scott Key Fitzgerald was an American writer of novels and short stories, whose works have been seen as evocative of the Jazz Age, a term he himself allegedly coined. He is regarded as one of the greatest twentieth century writers. Fitzgerald was of the self-styled 'Lost Generation,' Americans born in the 1890s who came of age during World War I. He finished four novels, left a fifth unfinished, and wrote dozens of short stories that treat themes of youth, despair, and age."})
orwell = Author.create({first_name:"George", last_name:"Orwell", year_born: 1903, year_died: 1950, image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/George-orwell-BBC.jpg", bio: "Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism. Orwell's influence on contemporary culture, popular and political, continues decades after his death. Several of his neologisms, along with the term 'Orwellian' — now a byword for any oppressive or manipulative social phenomenon opposed to a free society — have entered the vernacular."})
diaz = Author.create({first_name:"Junot", last_name:"Diaz", year_born: 1968, year_died: :nill, image: "http://news.mit.edu/sites/mit.edu.newsoffice/files/images/2012/20120910092107-0_0.jpg", bio: "Junot Díaz was born in the Dominican Republic and raised in New Jersey. He is the author of the critically acclaimed Drown; The Brief Wondrous Life of Oscar Wao, which won the 2008 Pulitzer Prize and the National Book Critics Circle Award; and This Is How You Lose Her, a New York Times bestseller and National Book Award finalist. He is the recipient of a MacArthur “Genius” Fellowship, PEN/Malamud Award, Dayton Literary Peace Prize, Guggenheim Fellowship, and PEN/O. Henry Award. A graduate of Rutgers College, Díaz is currently the fiction editor at Boston Review and the Rudge and Nancy Allen Professor of Writing at the Massachusetts Institute of Technology."})
atwood = Author.create({first_name:"Margaret", last_name:"Atwood", year_born: 1939, year_died: :nill, image: "https://d.gr-assets.com/authors/1282859073p8/3472.jpg", bio: "Margaret Atwood was born in 1939 in Ottawa and grew up in northern Ontario, Quebec, and Toronto. She received her undergraduate degree from Victoria College at the University of Toronto and her master's degree from Radcliffe College. Throughout her writing career, Margaret Atwood has received numerous awards and honourary degrees. She is the author of more than thirty-five volumes of poetry, children’s literature, fiction, and non-fiction and is perhaps best known for her novels."})
adichie = Author.create({first_name: "Chimamanda Ngozi", last_name: "Adichie", year_born: 1977, year_died: :nill, image: "https://d.gr-assets.com/authors/1366662981p8/11291.jpg", bio: "Chimamanda was born in Enugu, Nigeria, the fifth of six children to Igbo parents. She studied medicine and pharmacy at the University of Nigeria for a year and a half. At nineteen, Chimamanda left for the U.S. to study communication at Drexel University in Philadelphia for two years, then went on to pursue a degree in communication and political science at Eastern Connecticut State University. Chimamanda graduated summa cum laude from Eastern in 2001, and then completed a master's degree in creative writing at Johns Hopkins University, Baltimore."})

pi = Book.create({title: "Life of Pi", release_year: 2001, image: "https://upload.wikimedia.org/wikipedia/en/4/45/Life_of_Pi_cover.png", synopsis: "Life of Pi is a fantasy adventure novel by Yann Martel published in 2001. The protagonist, Piscine Molitor 'Pi' Patel, a Tamil boy from Pondicherry, explores issues of spirituality and practicality from an early age. He survives 227 days after a shipwreck while stranded on a boat in the Pacific Ocean with a Bengal tiger named Richard Parker."})
kavalier = Book.create({title: "The Amazing Adventures of Kavalier & Clay", release_year: 2000, image: "http://3.bp.blogspot.com/-6atNHO5r2pk/VOzrkEUrLAI/AAAAAAAAA60/7lUKDlv0IIw/s1600/gal-book-amazing-adventures-of-kavalier-and-clay-jpg.jpg", synopsis: "Joe Kavalier, a young Jewish artist who has also been trained in the art of Houdini-esque escape, has just smuggled himself out of Nazi-invaded Prague and landed in New York City. His Brooklyn cousin Sammy Clay is looking for a partner to create heroes, stories, and art for the latest novelty to hit America - the comic book. Drawing on their own fears and dreams, Kavalier and Clay create the Escapist, the Monitor, and Luna Moth, inspired by the beautiful Rosa Saks, who will become linked by powerful ties to both men. With exhilarating style and grace, Michael Chabon tells an unforgettable story about American romance and possibility."})
poisonwood = Book.create({title: "The Poisonwood Bible", release_year: 1998, image: "https://upload.wikimedia.org/wikipedia/en/7/79/Poisonwood_Bible.jpg", synopsis: "The Poisonwood Bible is a story told by the wife and four daughters of Nathan Price, a fierce, evangelical Baptist who takes his family and mission to the Belgian Congo in 1959. They carry with them everything they believe they will need from home, but soon find that all of it -- from garden seeds to Scripture -- is calamitously transformed on African soil. What follows is a suspenseful epic of one family's tragic undoing and remarkable reconstruction over the course of three decades in postcolonial Africa."})
gatsby = Book.create({title: "The Great Gatsby", release_year: 1925, image: "http://a5.files.biography.com/image/upload/c_fit,cs_srgb,dpr_1.0,q_80,w_300/MTI5MzY0OTk4NTM0MjQwNzM0.jpg", synopsis: "F. Scott Fitzgerald’s third book stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted “gin was the national drink and sex the national obsession,” it is an exquisitely crafted tale of America in the 1920s."})
oscar_wao = Book.create({title: "The Brief Wonderous Life of Oscar Wao", release_year: 2007, image: "http://pictures.abebooks.com/isbn/9781594483592-us-300.jpg", synopsis: "With dazzling energy and insight, Junot Díaz immerses us in the uproarious lives of our hero Oscar, his runaway sister Lola, and their ferocious beauty-queen mother Belicia, and in the epic journey from Santo Domingo to Washington Heights to New Jersey's Bergenline and back again. Rendered with uncommon warmth and humor, The Brief Wondrous Life of Oscar Wao presents an astonishing vision of the contemporary American experience and the endless human capacity to persevere - and to risk it all - in the name of love."})
lose_her = Book.create({title: "This Is How You Lose Her", release_year: 2012, image: "https://upload.wikimedia.org/wikipedia/en/a/a3/Original_cover_of_This_is_How_You_Lose_Her.jpg", synopsis: "On a beach in the Dominican Republic, a doomed relationship flounders. In the heat of a hospital laundry room in New Jersey, a woman does her lover’s washing and thinks about his wife. In Boston, a man buys his love child, his only son, a first baseball bat and glove. At the heart of these stories is the irrepressible, irresistible Yunior, a young hardhead whose longing for love is equaled only by his recklessness--and by the extraordinary women he loves and loses: artistic Alma; the aging Miss Lora; Magdalena, who thinks all Dominican men are cheaters; and the love of his life, whose heartbreak ultimately becomes his own."})
summer = Book.create({title: "Prodigal Summer", release_year: 2000, image: "http://ecx.images-amazon.com/images/I/51habVcrqdL._SX316_BO1,204,203,200_.jpg", synopsis: "Prodigal Summer weaves together three stories of human love within a larger tapestry of lives inhabiting the forested mountains and struggling small farms of southern Appalachia. Over the course of one humid summer, these characters find their connections to one another and to the flora and fauna with whom they share a place. Prodigal Summer demonstrates a balance of narrative, drama and ideas that is characteristic of Barbara Kingsolver's finest work."})
bean_trees = Book.create({title: "The Bean Trees", release_year: 1988, image: "http://d.gr-assets.com/books/1443483961l/30868.jpg", synopsis: "Clear-eyed and spirited, Taylor Greer grew up poor in rural Kentucky with the goals of avoiding pregnancy and getting away. But when she heads west with high hopes and a barely functional car, she meets the human condition head-on. By the time Taylor arrives in Tucson, Arizona, she has acquired a completely unexpected child, a three-year-old American Indian girl named Turtle, and must somehow come to terms with both motherhood and the necessity for putting down roots. Hers is a story about love and friendship, abandonment and belonging, and the discovery of surprising resources in apparently empty places."})
wonder_boys = Book.create({title: "Wonder Boys", release_year: 1995, image: "http://ecx.images-amazon.com/images/I/51iR93jD2uL.jpg", synopsis: "In his first novel since The Mysteries of Pittsburgh, Chabon presents a hilarious and heartbreaking work—the story of the friendship between the “wonder boys”—Grady, an aging writer who has lost his way, and Crabtree, whose relentless debauchery is capsizing his career."})
eighty_four = Book.create({title: "1984", release_year: 1949, image: "https://d.gr-assets.com/books/1348990566l/5470.jpg", synopsis: "The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever. 1984 is still the great modern classic of 'negative utopia' -a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions -a power that seems to grow, not lessen, with the passage of time."})
amer = Book.create({title: "Americanah", release_year: 2013, image: "http://ecx.images-amazon.com/images/I/51mSJNECGyL.jpg", synopsis: "From the award-winning author of Half of a Yellow Sun, a dazzling new novel: a story of love and race centered around a young man and woman from Nigeria who face difficult choices and challenges in the countries they come to call home."})

martel.books << pi
chabon.books << [kavalier, wonder_boys]
kingsolver.books << [poisonwood, summer, bean_trees]
fitzgerald.books << gatsby
diaz.books << [oscar_wao, lose_her]
orwell.books << eighty_four
adichie.books << amer

guest = User.create({name: "Guest", email: "guest@test.com", password: "mylibrary"})
